using System.Text.Json.Serialization;

namespace EuDecorator.Controllers.Dtos;

/// <summary>
/// 3.8.4.2 Validation Access Token Header
/// To allow a validation process, the validation access token is generated by the service provider. The
/// token follows the format of the JWT definition(RFC7519) and contains details about the necessary
/// validation.The token is signed with the service provider’s private key.The associated public key is
/// known by the validation provider and can be selected by the kid.
/// </summary>
public class ValidationAccessTokenHeader
{
    /// <summary>
    /// TODO ???? as JWT...
    /// </summary>
    [JsonPropertyName("typ")]
    public string Type { get; set; }

    /// <summary>
    /// SiES256/PS256 /RS256
    /// </summary>
    [JsonPropertyName("alg")]
    public string SignatureAlgorithm { get; set; }

    /// <summary>
    /// AccessTokenSigningKey-X KID
    /// Used key for signing. This key must be presented in the downloaded identity document.
    /// </summary>
    [JsonPropertyName("kid")]
    public string KeyId { get; set; }

    /// <summary>
    /// TODO do we agree this belongs in the access token?
    /// </summary>
    public Trip Trip { get; set; }

    /// <summary>
    /// With or without token?
    /// </summary>
    public string ResultCallBackUri { get; set; }
}