using System.Text.Json.Serialization;

namespace EuDecorator.Controllers.Dtos;

/// <summary>
/// 3.10.2.2.3 Request Body
/// The request body is a JSON structure which defines the user generated pubkey, the used key type and the subject.
/// </summary>
public class ValidationInitializeRequestBody
{
    /// <summary>
    /// ECDSA/RSA-PSS Key String Public Key generated by the user/wallet(x.509 PEM)
    /// </summary>
    [JsonPropertyName("pubKey")]
    public string WalletPublicKey { get; set; }


    /// <summary>
    /// ES256/PS256 /RS256 String Use Crypto Method according to JWT definitions in RFC75182 callback e.g.https://... String Optional Callback URL
    /// </summary>
    [JsonPropertyName("alg")]
    public string Algorithm { get; set; }


    /// <summary>
    /// TODO careful not to double encode requests/responses
    /// Random 16 bytes, Base64 encoded
    /// </summary>
    public string Nonce { get; set; }
}